config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  post '/process_payment', to: 'payments#process_payment'
  # Kullanıcı kaydı ve girişi için özel rotalar
  resources :sessions, only: [:create, :destroy]
  post '/register', to: 'users#create', as: :register
  post '/login', to: 'sessions#create', as: :login
  post '/logout', to: 'sessions#destroy', as: :logout

  # Kitaplarla ilgili rotalar
  resources :books, only: [:index, :show, :create, :update, :destroy]

  # Sepet öğeleriyle ilgili rotalar
  resources :cart_items, only: [:index, :show, :create, :update, :destroy]

  # Sepet ile ilgili rotalar
  resources :carts, only: [:index, :show, :create, :update, :destroy]

  # Sağlık durumu kontrolü için rota
  get '/up', to: 'rails/health#show', as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :publisher, presence: true
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
    has_many :cart_items
  end
  

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def calculate_total_price
    #self.total_price = cart_items.sum(&:subtotal)
    self.total_price = cart_items.where(cart_id: self.cart_id).sum(:subtotal)

  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :book

  def calculate_subtotal
    self.subtotal = quantity * book.price
    Cart.total_price = cart_items.where(cart_id: self.cart_id).sum(:subtotal)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  include ActionController::Cookies

  def authenticate_request!
    header = request.headers['Authorization']
    header = header.split(' ').last if header
    begin
      @decoded = JWT.decode(header, Rails.application.secret_key_base)
      @current_user = User.find(@decoded[0]['user_id'])
    rescue JWT::DecodeError
      render json: { error: 'Unauthorized' }, status: :unauthorized
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_request!
  before_action :set_book, only: [:show, :update, :destroy]
  # GET /books
  def index
    @books = Book.all
    render json: @books
  end

  # GET /books/:id
  def show
    render json: @book
  end

  # POST /books
  def create
    @book = Book.new(book_params)
    if @book.save
      render json: @book, status: :created
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /books/:id
  def update
    if @book.update(book_params)
      render json: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  # DELETE /books/:id
  def destroy
    @book.destroy
    render json: { message: 'Book was successfully destroyed' }, status: :ok
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :price)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_request!
  before_action :set_cart_item, only: [:show, :update, :destroy]

  # GET /cart_items
  def index
    @cart_items = CartItem.all
    render json: @cart_items
  end

  # GET /cart_items/:id
  def show
    render json: @cart_item
  end

  # POST /cart_items
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.calculate_subtotal  # Calculate subtotal
    if @cart_item.save
      render json: @cart_item, status: :created
    else
      render json: @cart_item.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cart_items/:id
  def update
    if @cart_item.update(cart_item_params)
      @cart_item.calculate_subtotal  
      render json: @cart_item
    else
      render json: @cart_item.errors, status: :unprocessable_entity
    end
  end


  # DELETE /cart_items/:id
  def destroy
    @cart_item.destroy
    @cart_item.calculate_subtotal  
    render json: { message: 'Cart item was successfully destroyed' }, status: :ok
  end

  private

  # Set the cart item before performing actions
  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through
  def cart_item_params
    params.require(:cart_item).permit(:cart_id, :book_id, :quantity, :subtotal)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_request!
  before_action :set_cart, only: [:show, :update, :destroy]

  # GET /carts
  def index
    @carts = Cart.all
    render json: @carts
  end

  # GET /carts/:id
  def show
    render json: @cart
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      render json: @cart, status: :created
    else
      render json: @cart.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /carts/:id
  def update
    if @cart.update(cart_params)
      render json: @cart
    else
      render json: @cart.errors, status: :unprocessable_entity
    end
  end

  # DELETE /carts/:id
  def destroy
    @cart.destroy
    render json: { message: 'Cart was successfully destroyed' }, status: :ok
  end

  private

  # Set the cart before performing actions
  def set_cart
    @cart = Cart.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through
  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_request!
  before_action :set_user_cart, only: [:process_payment]

  def process_payment
 
    cart_total_price = @user_cart.total_price
    
    payment_success = simulate_payment(cart_total_price)
    
    if payment_success
      @user_cart.cart_items.destroy_all
      render json: { message: 'Payment successful' }, status: :ok
    else
      render json: { error: 'Payment failed' }, status: :unprocessable_entity
    end
  end

  private

  def set_user_cart
    @user_cart = current_user.cart
  end

  def simulate_payment(total_price)
    true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ActionController::Cookies

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      token = generate_jwt(user)
      cookies.signed[:jwt] = {value: token, httponly: true}
      render json: { jwt: token }
    else
      render json: { error: 'Invalid username or password' }, status: :unauthorized
    end
  end

  def destroy
    cookies.delete(:jwt)
    render json: { message: 'Logged out successfully' }, status: :ok
  end

  private

  def generate_jwt(user)
    JWT.encode({ user_id: user.id, exp: 24.hours.from_now.to_i }, Rails.application.secret_key_base)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      render json: { message: 'User was successfully created.' }, status: :created
    else
      render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher, id: :book_publisher %>
  </div>

  <div class

app/views/books/edit.html.erb
<h1>Kitabı Düzenle: <%= @book.title %></h1>

<%= render 'form', book: @book %>

<%= link_to 'Geri Dön', books_path, class: 'btn btn-secondary' %>

app/views/books/index.html.erb
<h1>Kitap Listesi</h1>

<table>
  <thead>
    <tr>
      <th>Başlık</th>
      <th>Yazar</th>
      <th>Yayıncı</th>
      <th>Fiyat</th>
      <th>İşlemler</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= number_to_currency(book.price) %></td>
        <td>
          <%= link_to 'Görüntüle', book_path(book), class: 'btn btn-info' %>
          <%= link_to 'Düzenle', edit_book_path(book), class: 'btn btn-primary' %>
          <%= link_to 'Sil', book_path(book), method: :delete, data: { confirm: 'Bu kitabı silmek istediğinizden emin misiniz?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Yeni Kitap Ekle', new_book_path, class: 'btn btn-success' %>

app/views/books/new.html.erb
<h1>Yeni Kitap Ekle</h1>

<%= render 'form', book: @book %>

<%= link_to 'Geri Dön', books_path, class: 'btn btn-secondary' %>

app/views/books/show.html.erb
<h1>Kitap Detayları</h1>

<div>
  <strong>Başlık:</strong>
  <%= @book.title %>
</div>

<div>
  <strong>Yazar:</strong>
  <%= @book.author %>
</div>

<div>
  <strong>Yayıncı:</strong>
  <%= @book.publisher %>
</div>

<div>
  <strong>Fiyat:</strong>
  <%= number_to_currency(@book.price) %>
</div>

<%= link_to 'Düzenle', edit_book_path(@book), class: 'btn btn-primary' %>
<%= link_to 'Sil', book_path(@book), method: :delete, data: { confirm: 'Bu kitabı silmek istediğinizden emin misiniz?' }, class: 'btn btn-danger' %>
<%= link_to 'Tüm Kitaplar', books_path, class: 'btn btn-secondary' %>

app/views/cart_items/index.html.erb
<h1>Sepetinizdeki Ürünler</h1>

<table>
  <thead>
    <tr>
      <th>Kitap Adı</th>
      <th>Miktar</th>
      <th>Birim Fiyat</th>
      <th>Alt Toplam</th>
      <th>İşlemler</th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |item| %>
      <tr>
        <td><%= item.book.title %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.book.price) %></td>
        <td><%= number_to_currency(item.subtotal) %></td>
        <td>
          <%= link_to 'Sil', cart_item_path(item), method: :delete, data: { confirm: 'Bu öğeyi sepetinizden çıkarmak istediğinizden emin misiniz?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Yeni Ürün Ekle', new_cart_item_path, class: 'btn btn-success' %>

app/views/cart_items/show.html.erb
<h1>Sepet Öğesi Detayları</h1>

<p>
  <strong>Kitap Adı:</strong>
  <%= @cart_item.book.title %>
</p>

<p>
  <strong>Miktar:</strong>
  <%= @cart_item.quantity %>
</p>

<p>
  <strong>Birim Fiyat:</strong>
  <%= number_to_currency(@cart_item.book.price) %>
</p>

<p>
  <strong>Alt Toplam:</strong>
  <%= number_to_currency(@cart_item.subtotal) %>
</p>

<%= link_to 'Sepete Dön', cart_items_path, class: 'btn btn-secondary' %>

app/views/carts/index.html.erb
<h1>Sepetinizdeki Ürünler</h1>

<table>
  <thead>
    <tr>
      <th>Kitap Adı</th>
      <th>Miktar</th>
      <th>Birim Fiyat</th>
      <th>Alt Toplam</th>
      <th>İşlemler</th>
    </tr>
  </thead>
  <tbody>
    <% @cart_items.each do |item| %>
      <tr>
        <td><%= item.book.title %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.book.price) %></td>
        <td><%= number_to_currency(item.subtotal) %></td>
        <td>
          <%= link_to 'Sil', cart_item_path(item), method: :delete, data: { confirm: 'Bu öğeyi sepetinizden çıkarmak istediğinizden emin misiniz?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Yeni Ürün Ekle', new_cart_item_path, class: 'btn btn-success' %>

app/views/carts/show.html.erb
<!-- app/views/carts/show.html.erb -->

<h1>Sepetiniz</h1>

<% if @cart.cart_items.any? %>
  <table>
    <thead>
      <tr>
        <th>Kitap Adı</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Alt Toplam</th>
        <th>İşlemler</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.cart_items.each do |item| %>
        <tr>
          <td><%= item.book.title %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency(item.book.price) %></td>
          <td><%= number_to_currency(item.subtotal) %></td>
          <td>
            <%= link_to 'Sil', cart_item_path(item), method: :delete, data: { confirm: 'Bu öğeyi sepetinizden çıkarmak istediğinizden emin misiniz?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3"><strong>Total:</strong></td>
        <td><%= number_to_currency(@cart.total_price) %></td>
      </tr>
    </tfoot>
  </table>

  <%= link_to 'Öde', process_payment_path, method: :post, class: 'btn btn-success' %>
<% else %>
  <p>Sepetiniz boş.</p>
<% end %>

<%= link_to 'Kitap Listesi', books_path, class: 'btn btn-secondary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineBookManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Kullanıcı Kaydı</h1>

<%= form_with(model: @user, url: register_path, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prevented this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit "Kaydet", class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Giriş Yap', login_path, class: 'btn btn-secondary' %>